/*
-- Query: SELECT * FROM native_db.sample_content
LIMIT 0, 10000

-- Date: 2016-11-17 21:23
*/
USE native_db;

INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (1,'16.1/1872','Mask, Geeyikumhl','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%2E1%2F%201872','//mediaportal.rrncommunity.org/system/media/9/original/1254405IN1HKCBC80.jpg','mask','wood','Kwakwaka\'wakw','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (2,'16.1/1141','Mask','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%2E1%2F%201141','//mediaportal.rrncommunity.org/system/media/9/original/1253821Y0T0AHDBS3.jpg','mask','wood','Kwakwaka\'wakw','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (3,'16/9975','Mask, Hoxhoku','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209975','//mediaportal.rrncommunity.org/system/media/9/original/1253107PUHWDAKJIH.jpg','mask','wood','Kwakwaka\'wakw: Gwasila','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (4,'16/9684','Mask, Xwaixwe','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209684','//mediaportal.rrncommunity.org/system/media/9/original/1252899NMLISP01IO.jpg','mask','wood','Kwakwaka\'wakw','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (5,'16/9587','Mask, Wasp','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209587','//mediaportal.rrncommunity.org/system/media/9/original/1252812CBHGBRTQ4C.jpg','mask','wood','Kwakwaka\'wakw: Denax.Dax','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (6,'16/9586','Mask','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209586','//mediaportal.rrncommunity.org/system/media/9/original/12528115LTZ5O088W.jpg','mask','wood','Kwakwaka\'wakw: Denax.Dax','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (7,'16/9585','Mask, Mountain Goat','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209585','//mediaportal.rrncommunity.org/system/media/9/original/125281097RS8RNSQM.jpg','mask','wood','Kwakwaka\'wakw: Dza\'wadeenox','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (8,'16/9014','Mask, Dzonokwa','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%209014','//mediaportal.rrncommunity.org/system/media/9/original/12523116T76AOWU2V.jpg','mask','wood','Kwakwaka\'wakw','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (9,'16/8968','Mask, Killer Whale','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%208968','//mediaportal.rrncommunity.org/system/media/9/original/12522659KAFWZWHPN.jpg','mask','wood','Kwakwaka\'wakw: Nak\'wagdox: Teguxste','American Museum of Natural History');
INSERT INTO `sample_content` (`id`,`source_id`,`item_name`,`original_url`,`image_url`,`item_types`,`materials`,`cultures`,`institution`) VALUES (10,'16/8960','Mask','https://anthro.amnh.org/anthropology/databases/common/image_dup.cfm?catno=16%20%20%2F%208960','//mediaportal.rrncommunity.org/system/media/9/original/1252258BGXS65V2BO.jpg','mask','wood','Kwakwaka\'wakw','American Museum of Natural History');
